name: PM2.5 Data Logger and Teams Notifier

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python main.py
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pm25-data
          path: PM2.5_*.csv
