name: PM2.5 Logger and Teams Notifier

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas requests openpyxl

      - name: Run script
        run: python main.py
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}

      - name: Commit CSV to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add PM2.5_*.csv
          git commit -m "Add hourly PM2.5 CSV" || echo "No changes to commit"
          git push
